version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db   # Use service name
      POSTGRES_DB: social_network  # Your database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"









